language: python

python:
  - "2.7"

addons:
  firefox: "64.0"

services:
  - xvfb

env:
  - DJANGO_VERSION=1.11

before_install: 
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-linux64.tar.gz
  - mkdir geckodriver && tar zxvf geckodriver-v0.23.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver

install:
  - pip install -r requirements.txt

script:
  - cd src
  - xvfb-run python manage.py test -v 2
