version: "3"

services:
  spdx:
    container_name: spdx_prod
    build:
      context: ./
      dockerfile: dockerfile.prod
    ports:
      - 8000:8000
    volumes:
      - ./container_logs:/spdx/container_logs
    environment:
      - PYTHONDONTWRITEBYTECODE=1
    depends_on:
      - redis

  redis:
    image: redis:5.0-alpine
    container_name: redis
    restart: always
    volumes:
      - data-volume:/data
    ports:
      - 6379:6379

volumes:
  data-volume:
